apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config: |
    exporters:
      debug: {}
      # Will be removed in a future release.
      # Use the debug exporter instead.
      logging: {}
    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      memory_ballast: {}
    processors:
      batch: {}
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter: null
    receivers:
      jaeger:
        protocols:
          grpc: 
            # endpoint: tracing.istio-system.svc.cluster.local:32460
            # endpoint: 192.168.2.100:4317
            endpoint: 192.168.2.100:31461
          thrift_http:
            #          endpoint: ${env:MY_POD_IP}:14268
            endpoint: 192.168.2.100:30188
      #        thrift_compact:
      #          endpoint: ${env:MY_POD_IP}:6831
      otlp:
        protocols:
          grpc:
            #          endpoint: ${env:MY_POD_IP}:4317
            endpoint: 192.168.2.100:31461
          http:
            #          endpoint: ${env:MY_POD_IP}:4318
            endpoint: 192.168.2.100:30188
      # 它指定了要抓取的目标以及抓取的间隔时间
      # 抓取${env:MY_POD_IP}（Pod的IP地址）的端口
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - 0.0.0.:8888
      zipkin:
        endpoint: tracing.istio-system.svc.cluster.local:9411
    service:
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        logs:
          exporters:
            - debug
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - debug
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces:
          exporters:
            - debug
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - jaeger
            - zipkin
