apiVersion: v2
appVersion: 1.3.6
dependencies:
- name: higress-core
  repository: file://../core
  version: 1.3.6
- name: higress-console
  repository: https://higress.io/helm-charts/
  version: 1.3.3
description: Helm chart for deploying Higress gateways
home: http://higress.io/
icon: https://higress.io/img/higress_logo_small.png
keywords:
- higress
- gateways
name: higress
sources:
- http://github.com/alibaba/higress
type: application
version: 1.3.6
